export const ListingsData = [
  {
    id: '602438a99ef91c56415d2a16',
    name: 'Volkman - Douglas',
    description:
      'Quia laboriosam dolor consequatur vero qui voluptatem dolorum temporibus. Enim fuga minima ut delectus sit est est. Quia voluptatem deserunt eos eligendi. Ipsam accusantium incidunt consequatur aliquid. Quia totam quis doloremque laboriosam nihil illo molestias officia. Non voluptates ut repellat earum harum.',
    phone: '467-576-6947',
    email: 'volkmandouglas@yahoo.com',
    categories: ['automotive', 'beauty', 'music'],
    image: 'https://placeimg.com/160/160/transport',
    largeImage: 'https://placeimg.com/720/600/transport',
    websiteUrl: 'http://jakayla.org',
  },
  {
    id: '602438a99ef91c56415d2a17',
    name: 'Cormier Group',
    description:
      'Praesentium sapiente maiores corrupti tempora molestias accusamus illum eum. Officia iure tempora rerum quod veritatis quia nihil. Consequuntur ullam est voluptate unde quo nihil. Eum sunt dolor vel odio quam quibusdam laboriosam qui.',
    phone: '610-332-9675',
    email: 'cormiergroup@mail.com',
    categories: ['grocery', 'shoes', 'games', 'sports'],
    image: 'https://placeimg.com/160/160/sports',
    largeImage: 'https://placeimg.com/720/600/sports',
    websiteUrl: 'http://dedric.com',
  },
  {
    id: '602438a99ef91c56415d2a18',
    name: 'Jenkins and Heidenreich',
    description:
      'Quia laboriosam dolor consequatur vero qui voluptatem dolorum temporibus. Enim fuga minima ut delectus sit est est. Quia voluptatem deserunt eos eligendi. Ipsam accusantium incidunt consequatur aliquid. Quia totam quis doloremque laboriosam nihil illo molestias officia. Non voluptates ut repellat earum harum.',
    phone: '521-294-6664',
    email: 'jenkinsheidenreich@yahoo.com',
    categories: ['sports', 'garden'],
    image: 'https://placeimg.com/160/160/city',
    largeImage: 'https://placeimg.com/720/600/city',
    websiteUrl: 'http://regan.net',
  },
  {
    id: '602438a99ef91c56415d2a19',
    name: 'Rosenbaum Group',
    description:
      'Quia laboriosam dolor consequatur vero qui voluptatem dolorum temporibus. Enim fuga minima ut delectus sit est est. Quia voluptatem deserunt eos eligendi. Ipsam accusantium incidunt consequatur aliquid. Quia totam quis doloremque laboriosam nihil illo molestias officia. Non voluptates ut repellat earum harum.',
    phone: '780-936-8543',
    email: 'rosenbaumgroup@yahoo.com',
    categories: ['automotive', 'games', 'shoes'],
    image: 'https://placeimg.com/160/160/business',
    largeImage: 'https://placeimg.com/720/600/business',
    websiteUrl: 'https://tate.com',
  },
  {
    id: '602438a99ef91c56415d2a1a',
    name: 'Kiehn Group',
    description:
      'Quia laboriosam dolor consequatur vero qui voluptatem dolorum temporibus. Enim fuga minima ut delectus sit est est. Quia voluptatem deserunt eos eligendi. Ipsam accusantium incidunt consequatur aliquid. Quia totam quis doloremque laboriosam nihil illo molestias officia. Non voluptates ut repellat earum harum.',
    phone: '989-510-3607',
    email: 'kiehngroup@yahoo.com',
    categories: ['books', 'computers'],
    image: 'https://placeimg.com/160/160/technics',
    largeImage: 'https://placeimg.com/720/600/technics',
    websiteUrl: 'http://francisco.info',
  },
  {
    id: '602438a99ef91c56415d2a1b',
    name: 'Stamm Inc',
    description:
      'Quia laboriosam dolor consequatur vero qui voluptatem dolorum temporibus. Enim fuga minima ut delectus sit est est. Quia voluptatem deserunt eos eligendi. Ipsam accusantium incidunt consequatur aliquid. Quia totam quis doloremque laboriosam nihil illo molestias officia. Non voluptates ut repellat earum harum.',
    phone: '374-493-0601',
    email: 'stamminc@yahoo.com',
    categories: ['health', 'grocery'],
    image: 'https://placeimg.com/160/160/animals',
    largeImage: 'https://placeimg.com/720/600/animals',
    websiteUrl: 'https://virginie.net',
  },
  {
    id: '602438a99ef91c56415d2a1c',
    name: 'Treutel and Sons',
    description:
      'Quia laboriosam dolor consequatur vero qui voluptatem dolorum temporibus. Enim fuga minima ut delectus sit est est. Quia voluptatem deserunt eos eligendi. Ipsam accusantium incidunt consequatur aliquid. Quia totam quis doloremque laboriosam nihil illo molestias officia. Non voluptates ut repellat earum harum.',
    phone: '686-220-3722',
    email: 'treutelandsons@yahoo.com',
    categories: ['beauty'],
    image: 'https://placeimg.com/160/160/abstract',
    largeImage: 'https://placeimg.com/720/600/abstract',
    websiteUrl: 'http://grace.name',
  },
  {
    id: '602438a99ef91c56415d2a1d',
    name: 'Baumbach Inc',
    description:
      'Quia laboriosam dolor consequatur vero qui voluptatem dolorum temporibus. Enim fuga minima ut delectus sit est est. Quia voluptatem deserunt eos eligendi. Ipsam accusantium incidunt consequatur aliquid. Quia totam quis doloremque laboriosam nihil illo molestias officia. Non voluptates ut repellat earum harum.',
    phone: '749-377-3258',
    email: 'baumbachinc@yahoo.com',
    categories: ['music', 'movies', 'games'],
    image: 'https://placeimg.com/160/160/food',
    largeImage: 'https://placeimg.com/720/600/food',
    websiteUrl: 'http://ebba.info',
  },
  {
    id: '602438a99ef91c56415d2a1e',
    name: 'Rutherford and Sons',
    description:
      'Quia laboriosam dolor consequatur vero qui voluptatem dolorum temporibus. Enim fuga minima ut delectus sit est est. Quia voluptatem deserunt eos eligendi. Ipsam accusantium incidunt consequatur aliquid. Quia totam quis doloremque laboriosam nihil illo molestias officia. Non voluptates ut repellat earum harum.',
    phone: '719-950-3842',
    email: 'rutherfordandsons@yahoo.com',
    categories: ['jewelery', 'clothing'],
    image: 'https://placeimg.com/160/160/people',
    largeImage: 'https://placeimg.com/720/600/people',
    websiteUrl: 'http://dario.info',
  },
  {
    id: '602438a99ef91c56415d2a1f',
    name: 'Parker - Carter',
    description:
      'Quia laboriosam dolor consequatur vero qui voluptatem dolorum temporibus. Enim fuga minima ut delectus sit est est. Quia voluptatem deserunt eos eligendi. Ipsam accusantium incidunt consequatur aliquid. Quia totam quis doloremque laboriosam nihil illo molestias officia. Non voluptates ut repellat earum harum.',
    phone: '525-690-7380',
    email: 'parkercarter@yahoo.com',
    categories: ['movies', 'home'],
    image: 'https://placeimg.com/160/160/nature',
    largeImage: 'https://placeimg.com/720/600/nature',
    websiteUrl: 'http://kip.org',
  },
  {
    id: '602438a99ef91c56415d2a20',
    name: 'Huel Group',
    description:
      'Quia laboriosam dolor consequatur vero qui voluptatem dolorum temporibus. Enim fuga minima ut delectus sit est est. Quia voluptatem deserunt eos eligendi. Ipsam accusantium incidunt consequatur aliquid. Quia totam quis doloremque laboriosam nihil illo molestias officia. Non voluptates ut repellat earum harum.',
    phone: '638-588-1578',
    email: 'huelgroup@yahoo.com',
    categories: ['games', 'shoes'],
    image: 'https://placeimg.com/160/160/fashion',
    largeImage: 'https://placeimg.com/720/600/fashion',
    websiteUrl: 'http://colton.info',
  },
  {
    id: '602438a99ef91c56415d2a21',
    name: 'Kuhic - Fay',
    description:
      'Quia laboriosam dolor consequatur vero qui voluptatem dolorum temporibus. Enim fuga minima ut delectus sit est est. Quia voluptatem deserunt eos eligendi. Ipsam accusantium incidunt consequatur aliquid. Quia totam quis doloremque laboriosam nihil illo molestias officia. Non voluptates ut repellat earum harum.',
    phone: '615-522-2237',
    email: 'kuhicfay@yahoo.com',
    categories: ['games'],
    image: 'https://placeimg.com/160/160/nightlife',
    largeImage: 'https://placeimg.com/720/600/nightlife',
    websiteUrl: 'http://guillermo.biz',
  },
]
